version: '3.8'

services:
  db:
    image: postgis/postgis:17-3.5
    container_name: farm-twin-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Employee@123
      POSTGRES_DB: farm_twin
    ports:
      - "5436:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: farm-twin-backend
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/farm_twin
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Employee@123
    volumes:
      - uploads-data:/app/uploads
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: farm-twin-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pgdata:
    driver: local
  uploads-data:
    driver: local
